version: "3.7"

services:

  app:
    image: perl-mojo
    ports:
      - 3000:8080
    volumes:
      - ./app:/usr/src/myapp
    command: ["morbo", "./myapp.pl", "daemon",
      "-m", "production",
      "-l", "http://*:8080"
    ]

  postgresql:
    image: postgres:16.0
    ports:
      - 5432:5432
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
      - ./app/bin/init-sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: perl-mojo
      POSTGRES_PASSWORD: mypassword